# Generated by Django 4.2.4 on 2023-08-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='f_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='l_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
