# Generated by Django 4.2.4 on 2024-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/user_images/default.png', upload_to='media/user_images/'),
        ),
    ]
