# Generated by Django 4.2.4 on 2024-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
